package pojo;
// Generated Oct 1, 2021 11:35:14 AM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import DAO.DAOProduct;
import java.util.List;
import javax.faces.bean.ManagedBean;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Product generated by hbm2java
 */
@ManagedBean
public class Product  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String genre;
     private String developer;
     private int stock;
     
    public List<Product> getAllRecords() {
        DAOProduct product = new DAOProduct();
        List<Product> listProduct = product.retrveTblproduct();
        return listProduct;
    }
    
    public String getById() {
        String idProduct = id.toString();
        DAOProduct product = new DAOProduct();
        List<Product> listProduct = product.getbyID(idProduct);
        try {
            if (listProduct != null) {
                name = listProduct.get(0).name;
                genre = listProduct.get(0).genre;
                developer = listProduct.get(0).developer;
                stock = listProduct.get(0).stock;
                return "dashboard";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "dashboard_error_search";
    }
    
    public String saveProduct() {
        DAOProduct product = new DAOProduct();
        product.addProduct(this);
        name = "";
        genre = "";
        developer = "";
        stock = 0;
        return "dashboard";
    }
    
    public String editProduct() {
        DAOProduct product = new DAOProduct();
        product.editUser(this);
        name = "";
        genre = "";
        developer = "";
        stock = 0;
        return "dashboard";
    }
    
    public String deleteProduct() {
        DAOProduct product = new DAOProduct();
        product.deleteUser(id);
        name = "";
        genre = "";
        developer = "";
        stock = 0;
        return "dashboard";
    }

    public Product() {
    }

    public Product(String name, String genre, String developer, int stock) {
       this.name = name;
       this.genre = genre;
       this.developer = developer;
       this.stock = stock;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public String getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(String developer) {
        this.developer = developer;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
}


